# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"diffusion_curvature": "01_Diffusion Curvature of Directed Graphs.ipynb",
         "diffusion_matrix_from_graph": "02_Directed_graph_utils.ipynb",
         "curvature": "12_differentiable_diffusion_curvature.ipynb"}

modules = ["curvature.py",
           "utils.py",
           "differentiable_laziness.py"]

doc_url = "https://professorwug.github.io/directed_graphs/"

git_url = "https://github.com/professorwug/directed_graphs/tree/master/"

def custom_doc_links(name): return None
