# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"diffusion_curvature": "01_Diffusion Curvature of Directed Graphs.ipynb",
         "diffusion_matrix_from_graph": "02_Directed_graph_utils.ipynb",
         "node2vec_and_plot": "04_testing node2vec on directed graphs.ipynb",
         "deepwalk_and_pca_plot": "06_Node2Vec_with_Backwards_Connection.ipynb",
         "curvature": "12_differentiable_diffusion_curvature.ipynb",
         "diffusion_curvature_of_graph": "12_differentiable_diffusion_curvature.ipynb",
         "EmailEuNetwork": "21_Communities_Datasets.ipynb",
         "SourceSink": "21_Communities_Datasets.ipynb",
         "SmallRandom": "22_Small_Random_Directed_Graphs.ipynb",
         "visualize_graph": "22_Small_Random_Directed_Graphs.ipynb",
         "DirectedStochasticBlockModel": "24_Directed Stochastic Block Model.ipynb",
         "source_graph": "24_Directed Stochastic Block Model.ipynb",
         "sink_graph": "24_Directed Stochastic Block Model.ipynb",
         "ChainGraph": "24_Directed Stochastic Block Model.ipynb",
         "ChainGraph2": "24_Directed Stochastic Block Model.ipynb",
         "ChainGraph3": "24_Directed Stochastic Block Model.ipynb",
         "CycleGraph": "24_Directed Stochastic Block Model.ipynb",
         "GeneralFlowEmbedder": "33_Flow_Embedding_with_Implicit_Vectors.ipynb",
         "DirectedStochasticBlockModelHelper": "41_node2vec_graph_reversal_walk.ipynb"}

modules = ["curvature.py",
           "utils.py",
           "embeddings.py",
           "differentiable_laziness.py",
           "datasets.py"]

doc_url = "https://professorwug.github.io/directed_graphs/"

git_url = "https://github.com/professorwug/directed_graphs/tree/master/"

def custom_doc_links(name): return None
