---
title: "999_Rna_velocity"
output: html_document
date: '2022-06-29'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readr)
```

```{r}
if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("pcaMethods")
library(devtools)
install_github("velocyto-team/velocyto.R")
library(velocyto.R)



nuc_gexp = as.matrix(read.csv("~/project/directed_graphs/datasets/email_Eu_network/raw/pnas.1912459116.sd14.csv", row.names=1))
print(cell_gexp[1:5,1:5])
```
```{r}
fac2col <- function(x,s=1,v=1,shuffle=FALSE,min.group.size=1,return.details=F,unclassified.cell.color='gray50',level.colors=NULL) {
  x <- as.factor(x);
  if(min.group.size>1) {
    x <- factor(x,exclude=levels(x)[unlist(tapply(rep(1,length(x)),x,length))<min.group.size])
    x <- droplevels(x)
  }
  if(is.null(level.colors)) {
    col <- rainbow(length(levels(x)),s=s,v=v);
  } else {
    col <- level.colors[1:length(levels(x))];
  }
  names(col) <- levels(x);

  if(shuffle) col <- sample(col);

  y <- col[as.integer(x)]; names(y) <- names(x);
  y[is.na(y)] <- unclassified.cell.color;
  if(return.details) {
    return(list(colors=y,palette=col))
  } else {
    return(y);
  }
}

## quick utility to check if given character vector is colors
## thanks, Josh O'Brien: http://stackoverflow.com/questions/13289009/check-if-character-string-is-a-valid-color-representation
areColors <- function(x) {
  is.character(x) &
  sapply(x, function(X) {
    tryCatch(is.matrix(col2rgb(X)), error = function(e) FALSE)
  })
}
```

```{r}
## Derive cytoplasmic expression
cyto_gexp = cell_gexp - nuc_gexp

## Keep cluster labels from previously
cluster.label = factor(com)
cell.colors = fac2col(cluster.label)

## Limit to same batch of cells as previously
emat0 <- cyto_gexp[, subcells]
nmat0 <- nuc_gexp[, subcells]
```

```{r}
## mRNA only
library(biomaRt)
# mart <- useMart(biomart = "ensembl", dataset = "hsapiens_gene_ensembl") # latest version was crashing Rmd build
mart <- useMart(biomart = "ENSEMBL_MART_ENSEMBL", dataset = 'hsapiens_gene_ensembl') 
results <- getBM(attributes=c('hgnc_symbol', "transcript_biotype"),
                filters = 'hgnc_symbol',
                values = rownames(cd),
                mart = mart)
head(results)
```

```{r}
table(results$transcript_biotype)
```

```{r}
mrnas <- results$hgnc_symbol[results$transcript_biotype == 'protein_coding']
mrnas <- intersect(good.genes, 
                   unique(mrnas))
length(mrnas)
```

```{r}
emat <- emat0[mrnas,]
nmat <- nmat0[mrnas,]
```

```{r}
rvel.cd.unpooled <- gene.relative.velocity.estimates(emat, nmat,
                                           fit.quantile = 0.05,
                                           min.nmat.emat.correlation = 0.2, 
                                           min.nmat.emat.slope = 0.2, 
                                           kCells = 1)
```








